// desafio_em_vue/src/components/FooterComponent/Footer.vue
<!--  -->
<template>

    <footer>
        <div>

            <button @click="handleClick(name)">

                <img :src="src" :alt="name">
            
                <!-- <p>{{ titleTeste }}</p> -->
            
                <!-- <p>{{ translateTeste }}</p> -->
            
            </button>

        </div>

    </footer>

</template>

<!--  -->
<script>

export default {
    name: 'FooterComponent',

    props: {
        title: String,
        flags: {}
    },

    data() {
        return {
            titleTeste: this.title,
            name: this.flags.name,
            src: this.flags.src,
            // translateTeste: this.flags
        }
    },

    methods: {
        handleClick(name) {
                // this.titleTeste = this.technologies.name
                this.$emit('changeTitle', name)
            }
    }
}

</script>

// Desafio_em_Angular/src/app/components/footer/footer.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.sass']
})
export class FooterComponent {

  @Input() flags!: {name: string; flag: string;
    metodo: () => void};

  @Output()
  language = new EventEmitter();

  handleClick(): void {
    this.language.emit(this.flags.name);
  }

}


<div ng ngClass="botao_footer">

  <button title="#" (click)="handleClick()">

    <img ngClass="flag" src={{flags.flag}} alt={{flags.name}}>
    <p ngClass="txt_flag">{{flags.name}}</p>

  </button>
</div>
