// desafio_em_vue/src/components/HeaderComponent/Header.vue
<!--  -->
<template>
    
    <header>

        <div>
            <a v-bind:href="site_stack" target="_blank">
                <img src="../../assets/images/logoStackx.svg" alt="Logo StackX">
            </a>
        </div>

    </header>

</template>

<!--  -->
<script>
    export default {
        name: 'HeaderComponent',
         
        data() {
            return {
                site_stack: 'https://academia.stackx.com.br/'
            }
        }
    }
</script>

// Desafio_em_React/src/components/Header/index.tsx
import { 
    Container,
    Content,
    ImageLogo,
} from './styles';

import logoSvg from '../../assets/icons/logo.svg';

export function Header() {
    return (
        <Container>
            <Content>
                <a href={'https://academia.stackx.com.br/'} target='_blank' title='stackx'>
                    <ImageLogo  src={logoSvg} alt='logo' />
                </a>
            </Content>
        </Container>
    );
};
