// Desafio_em_Angular/src/app/components/list-techs/list-techs.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-list-techs',
  templateUrl: './list-techs.component.html',
  styleUrls: ['./list-techs.component.scss']
})
export class ListTechsComponent {

  techs = ['JavaScript', 'React', 'Vue Js', 'Tailwind CSS', 'Styled Components', 'Saas', 'Node', 'TypeScript', 'Angular', 'Java'];

}

<!--  -->

<div ngClass="list-techs">
  <ul>
    <li *ngFor="let tech of techs"> {{ tech }} </li>
  </ul>

</div>

// Desafio_em_React/src/components/ListTechs/index.tsx
//
import { Container } from './styles';
import { ListButton } from '../ListButton'

type ListProps = {
    changeTitle: (params: string) => void;
}

export function ListTechs({ changeTitle }: ListProps) {

    const techs = [
        'JavaScript', 'React', 'Vue Js', 'Tailwind CSS', 'Styled Components', 'Saas', 'Node', 'TypeScript', 'Angular', 'Java'
    ];

    return (
        <Container>
            <ul>
                {
                    techs.map((tech, i) => {
                        return <li key={i}>
                            {<ListButton title={tech} changeTitle= {changeTitle} />}
                            </li>
                    })
                }
            </ul>
        </Container>

    );
};
