// TesteReactDesafio/Desafio_em_React/src/components/Header/index.tsx
import { 
    Container,
    ImageLogo
} from './styles';
import logoStack from '../../assets/icons/logoStackx.svg'

function Header() {
    return(
        <Container>
            <a href={'https://academia.stackx.com.br/'} target='_blank' title='Logo StackX'>
                    <ImageLogo  src={logoStack} alt="Logo StackX" />
                </a>
        </Container>
    );
}

export default Header;

// desafio_em_vue/src/components/HeaderComponent/Header.vue
<!--  -->
<template>
    
    <header>

        <div>
            <a v-bind:href="site_stack" target="_blank">
                <img src="../../assets/images/logoStackx.svg" alt="Logo StackX">
            </a>
        </div>

    </header>

</template>

<!--  -->
<script>
    export default {
        name: 'HeaderComponent',
         
        data() {
            return {
                site_stack: 'https://academia.stackx.com.br/'
            }
        }
    }
</script>
