// desafio_em_vue/src/components/HeaderComponent/Header.vue
<!--  -->
<template>
    
    <header>

        <div>
            <a v-bind:href="site_stack" target="_blank">
                <img src="../../assets/images/logoStackx.svg" alt="Logo StackX">
            </a>
        </div>

    </header>

</template>

<!--  -->
<script>
    export default {
        name: 'HeaderComponent',
         
        data() {
            return {
                site_stack: 'https://academia.stackx.com.br/'
            }
        }
    }
</script>

// Desafio_em_Angular/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.sass']
})

export class HeaderComponent implements OnInit {

  logo = '../../../assets/images/logo.png'

  constructor() { }

  ngOnInit(): void {}

}


<header ngClass="container_header">

  <div ngClass="container-logo">

    <a href="https://academia.stackx.com.br/" target="_blank">
      <img ngClass="logo" src={{logo}} alt="Logo stackX">
    </a>

  </div>

</header>
